# Generated by Django 3.1.7 on 2021-02-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_time', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='policy_violation_noted',
            field=models.BooleanField(default=False),
        ),
    ]
