# Generated by Django 3.1.7 on 2021-02-23 17:04

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_time', '0002_auto_20210220_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelog',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='timelog',
            name='minute',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterUniqueTogether(
            name='timelog',
            unique_together={('date', 'created_by')},
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='hours',
        ),
    ]
