# Generated by Django 3.1.7 on 2021-02-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_time', '0003_auto_20210223_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timelog',
            old_name='minute',
            new_name='duration',
        ),
    ]
