// auth action types
// user
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const USER_REGISTERED = "USER_REGISTERED";
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR";

export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

export const AUTH_LOADING = "AUTH_LOADING";

export const USER_INFO_LOADED = "USER_INFO_LOADED";
export const USER_INFO_LOAD_ERROR = "USER_INFO_LOAD_ERROR";

// forget password
export const FORGET_PASSWORD_REQUEST_RESET_LOADING = "FORGET_PASSWORD_REQUEST_RESET_LOADING"
export const FORGET_PASSWORD_REQUEST_RESET_SUCCESS = "FORGET_PASSWORD_REQUEST_RESET_SUCCESS"
export const FORGET_PASSWORD_REQUEST_RESET_ERROR = "FORGET_PASSWORD_REQUEST_RESET_ERROR"

export const FORGET_PASSWORD_RESET_LOADING = "FORGET_PASSWORD_RESET_LOADING"
export const FORGET_PASSWORD_RESET_SUCCESS = "FORGET_PASSWORD_RESET_SUCCESS"
export const FORGET_PASSWORD_RESET_ERROR = "FORGET_PASSWORD_RESET_ERROR"

// time logs
export const TIME_LOGS_LOADED = "TIME_LOGS_LOADED"
export const TIME_LOGS_LOAD_ERROR = "TIME_LOGS_LOAD_ERROR"
export const TIME_LOGS_LOADING = "TIME_LOGS_LOADING"
export const TIME_LOG_SAVED = "TIME_LOG_SAVED"
export const TIME_LOG_SAVE_ERROR = "TIME_LOG_SAVE_ERROR"

export const TIME_LOG_LOADED = "TIME_LOG_LOADED" // for single log
export const TIME_LOG_LOAD_ERROR = "TIME_LOG_LOAD_ERROR"
export const TIME_LOG_LOADING = "TIME_LOG_LOADING"

// log report
export const LOG_REPORT_LOADING = "LOG_REPORT_LOADING"
export const LOG_REPORT_LOADED = "LOG_REPORT_LOADED"
export const LOG_REPORT_LOAD_ERROR = "LOG_REPORT_LOAD_ERROR"

// user
export const USERS_LOADING = "USERS_LOADING";
export const USERS_LOADED = "USERS_LOADED";
export const USERS_LOAD_ERROR = "USERS_LOAD_ERROR";

// user profile
export const USER_PROFILE_LOADING = "USER_PROFILE_LOADING";
export const USER_PROFILE_INFORMATION_LOADED = "USER_PROFILE_INFORMATION_LOADED";
export const USER_PROFILE_INFORMATION_LOAD_ERROR = "USER_PROFILE_INFORMATION_LOAD_ERROR";
export const USER_PROFILE_UPDATED = "USER_PROFILE_UPDATED";
export const USER_PROFILE_UPDATE_ERROR = "USER_PROFILE_UPDATE_ERROR";

export const USER_PASSWORD_UPDATED = "USER_PASSWORD_UPDATED";
export const USER_PASSWORD_UPDATE_ERROR = "USER_PASSWORD_UPDATE_ERROR";

export const COMPANY_DATA_LOADING = "COMPANY_DATA_LOADING"
export const COMPANY_DATA_LOADED = "COMPANY_DATA_LOADED"
export const COMPANY_DATA_LOAD_ERROR = "COMPANY_DATA_LOAD_ERROR"