# Generated by Django 3.1.7 on 2021-03-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210314_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('contractor', 'Contractor')], default='employee', max_length=20),
        ),
    ]
