# Generated by Django 3.1.7 on 2021-03-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_useraccount_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_company_owner',
            field=models.BooleanField(default=False),
        ),
    ]
